[package]
name = "sing-box-protocol-shadowquic"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
sing-box-core = { path = "../sing-box-core" }
sing-quic.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
